# Etapa 1: construir la app Angular
FROM node:20 AS build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install -g @angular/cli@20
RUN npm install
COPY frontend/ .
RUN ng build --configuration production

# Etapa 2: servir con Nginx
FROM nginx:stable-alpine
COPY --from=build /app/dist/ /usr/share/nginx/html
EXPOSE 80
